// <auto-generated />
namespace InteligenciaDigital.SAJ.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CriandoServidorTEF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriandoServidorTEF));
        
        string IMigrationMetadata.Id
        {
            get { return "201303192224012_Criando ServidorTEF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
