// <auto-generated />
namespace InteligenciaDigital.SAJ.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemocodeUsuaio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemocodeUsuaio));
        
        string IMigrationMetadata.Id
        {
            get { return "201308311610180_Remoco de Usuaio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
